version: 2

updates:
  # Dépendances Maven (Java)
  - package-ecosystem: "maven"
    directory: "."          # Chemin du pom.xml
    schedule:
      interval: "daily"    # daily | weekly | monthly
      day: "thursday"
      time: "06:00"
      timezone: "Africa/Casablanca"

    open-pull-requests-limit: 5

    # Mise à jour des dépendances directes et transitives
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

    # Message de commit
    commit-message:
      prefix: "deps"
      include: "scope"

    # Assignation et revue
    reviewers:
      - "FatimaGhi"
     
    assignees:
      - "FatimaGhi"

    # Regroupement des PRs (recommandé)
    groups:
      spring:
        patterns:
          - "org.springframework*"
